### ISSUE TITLE
Docs are wrong/misleading

### ISSUE THREAD

**Issue by Lusiphur** [Nadybot/Nadybot#442]
https://github.com/Nadybot/Nadybot/wiki/Packages

> systemctl enable --now nadyboot`

Should obviously be "nadybot"

All of the docker instructions under https://github.com/Nadybot/Nadybot/wiki/Running don't work. Specifically,

1. In the mariadb example it fails because no mariadb container is running. I assume you need to set one up but have no ideas what parameters to give it (name, credentials etc).
2. In the local sqlite example it creates /opt/aodb but does not create a database in there so nadybot command fails because it cannot find a db to connect to. If I look in the folder it is empty. There must be a step missing here.

**Comment by Nadyita** [comment]
Thanks for your feedback. I fixed the typo, but as for the rest: I never intended to write instructions how to run containers (docker or podman). The container-part of the docs is mainly for people who already know what they are doing. Explaining how to setup and run a MariaDB container is beyond the intended scope of this document. The same goes for systemd units. I only give examples, so people get an idea, how they can write one - not for them to be copy-and-paste-ready.

> In the local sqlite example it creates /opt/aodb but does not create a database in there so nadybot command fails because it cannot find a db to connect to. If I look in the folder it is empty. There must be a step missing here.

The bot is very likely just lacking access rights to create the database in that directory.

---

I'm not opposing writing these instructions. The problem is that I don't even *use* docker. I switched to podman a long time ago (back when it was still rkt, but that's a different story) and especially permission-issues are handled differently there. So if you want to help to improve these docs, you are very welcome to do so. Do I need to provide one full setup with all files? For MySQL and SQLite? Or just *some* more hints?

**Comment by Lusiphur** [comment]
> The bot is very likely just lacking access rights to create the database in that directory.

The directory was created by the bot running under systemd. So, if the permissions aren't right I have no idea what they should be as it would be reasonable to assume the bot would create the directory with the right permissions. It created the directory as root root so the bot definitely has sudo permissions. I am afraid I am at a loss as to what the permissions should be then.

I am happy to provide document updates when I can get it working. Right now I only have the information on that wiki page to go on.

**Comment by Nadyita** [comment]
It's not the bot that creates the directory – it's the docker daemon. Any directory mapped into a docker container automatically gets created if it didn't exist before.

The Nadybot process runs as uid:gid 1000:1000, so if you just `chown 1000:1000 /opt/aodb`, then the bot will have write access. But running Nadybot as your first Docker container is probably not a good idea, because mounting directories into a container has several security issues.

If changing the owner of the directory doesn't solve your problem, do a `chmod 0777 /opt/aodb` and check with which user id the database gets created.
